### ISSUE TITLE
Developer Contributions Stats Pipeline

### ISSUE THREAD

**Issue by pkudinov** [near/data-platform#24]
### Description

Create a contribution stats pipeline for the [Developer Contribution Board.
](https://github.com/near/data-platform/issues/7)

---

### Data Needed

| Value | Detail |
| -----| -----| 
| Name | _User's display name_ |
| Account ID | _User's account ID_ |
 | Total Components | _Total number of created components during selected timeframe_ |
 | Total Stars | _Total number of stars their components received during selected timeframe_ |
 | ~~Total Forks~~ | ~~_Total number of forks their components had during selected timeframe_~~ |
 | Total Commits |  _Total number of published code events during selected timeframe_ |
 | Total Lines of Code | _Total lines of code shipped during selected timeframe_ |
 | Start Date | _The date a user shipped their first line of BOS code_ |
 
- The pipeline should enable the above table to be created, for all time, this month == last 30 days, and last week == last 7 days

 ---

### Resources

-  [UX Figma Design](https://www.figma.com/proto/7NiPXGPT2ugQc7KBhSWHa7/Recommendations?page-id=722:1976&type=design&node-id=722-4665&viewport=-233,155,0.5&t=tcpnQMGsf3PyG4nA-1&scaling=min-zoom)

- Data can be based on `hive_metastore.near_social_developers_analytics.gold_daily_component_stats` table

**Comment by thisisjoshford** [comment]
I spoke with @Oksanusha the week before last about removing forks from this pipeline and just updated the ticket to strike out that field. Is this issue complete?

**Comment by jinouyang** [comment]
@Oksanusha what's the latest update on this?

**Comment by Oksanusha** [comment]
@jinouyang @thisisjoshford 
Hi guys! This is the last update. Please notice that the tag column is still in progress because, for some widgets, my code doesn't show the actual tags.

**Comment by s-n-park** [comment]
@Oksanusha  - heads up I think these 2 queries should be able to help you along:

1. Commits - I think this can actually be simplified considerably to count number of times that the widget field is not null:
[Query](https://4221960800361869.9.gcp.databricks.com/sql/editor/4fbadc42-7255-461e-ab0e-bc6f02e36bb6?o=4221960800361869) - using this [example](https://near.org/near/widget/ComponentDetailsPage?src=marketplacebos.near/widget/TrendingPost.ChartValueAll)

2. Tag keys - more complicated but essentially I think a decent method is to search through each of the widget keys specifically for the path "...:metadata:tags" and then pull json_object_keys to get the array of tags (see [query](https://4221960800361869.9.gcp.databricks.com/sql/editor/1502b8a1-5897-4572-9104-db156101037a?o=4221960800361869)) using [Neat](https://near.org/near/widget/ComponentDetailsPage?src=inscribe.near/widget/NEAT) as an example

I used a lot of your logic and just played around with a few examples, let me know if I can clarify anything!

**Comment by Oksanusha** [comment]
Hi @s-n-park!
Thanks for helping! I used these kind of queries, but it still has two issues:  the number of commits doesn't match for some widgets (I found that [our internal data](https://4221960800361869.9.gcp.databricks.com/sql/editor/4be58c3a-9fef-4987-b4d7-3022bf2de8ad?o=4221960800361869) has more commits than the commit's history [on the website](https://near.org/near/widget/ComponentDetailsPage?src=bluebiu.near/widget/ZKEVM-all-in-one&tab=source)),  and it's not easy to build a [query](https://4221960800361869.9.gcp.databricks.com/sql/editor/7a8b19e8-7474-4b90-bd03-9b273fbc5de3?o=4221960800361869) to show an actual list of tags for every date_utc, because some tags can be added and removed several times and other tags used only in one tx several weeks ago and they didn't reflect in the last commit, so again it doesn't match with [our website](https://near.org/near/widget/ComponentDetailsPage?src=bluebiu.near/widget/ZKEVM-all-in-one&tab=source).

**Comment by Oksanusha** [comment]
Perhaps the tags task can be resolved using udf

**Comment by Oksanusha** [comment]
@s-n-park Fantastic! Thank you so much!!!

**Comment by Oksanusha** [comment]
Hey there!
The [pipeline](https://4221960800361869.9.gcp.databricks.com/?o=4221960800361869#joblist/pipelines/cc96bc55-bda8-41dd-a65d-de89f441be32/updates/b3b081be-62a7-4b75-9620-92a63307c054) is done. I compared developers and widget information with widget data on near.org; randomly chosen widgets have identical data (number of commits, stars, unique dependencies, tags, discussions, website link)

The gold_near_social_widgets table shows widget information for every tx.

The gold_daily_component_stats  table shows aggregated information by every widget daily.

Gold_near_social_daily_weekly_monthly_new_developers, gold_near_social_monthly_top_10_code_line_writers, and gold_near_social_retention_rate tables stayed the same.

**Comment by Oksanusha** [comment]
Which columns are ready for review:

- developerAccountId (e.g. andyh.near)
- componentName (e.g. andyh.near/widget/StateDemoRoot.Trusted)
- date (e.g. 2023-10-01)
-  Measures:
- Total Number of components that use this component
- Total number of tags
- hasAppTag – whether it has an 'app' tag or not (true | false)
- hasWebsiteLink (true | false)
- Description text length
- Number of times it was loaded using public mainnet RPC (from RPC logs) on near.org
- Number of times it was loaded using public mainnet RPC (from RPC logs) in dev environment
- Number of times it was loaded using public mainnet RPC (from RPC logs) on all gateway
- Number of comments on the "Discussion tab" of the component details page
- Total Number of code lines
- Total number of commits


Which columns are work in progress:

- Number of times it rendered with errors
- Number of times its source code was viewed

Which columns are blocked:

- Fork data
