### ISSUE TITLE
Publish Fast Auth account chart to component for public link sharing

### ISSUE THREAD

**Issue by jinouyang** [near/data-platform#50]
Context: OurNetwork is looking to feature NEAR in its next L1 coverage. They ask for data driven insights with charts and source linked.

After discussion with Eric, we decided one of the bullet points should cover the success of Fast Auth. Thus we need to publish the chart to a component in order to provide the link of the data source. 

Timeline: The submission from our end is due EOD Nov 16 (ET). The newsletter goes live on Friday nov 17.

**Comment by eduohe** [comment]
Done: https://near.org/eduohe.near/widget/Analytics.FastAuthByDate
